version: "3.7"

services:
  redis:
    image: redis:7.2-alpine
    container_name: coupon-redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0
    container_name: coupon-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  master:
    image: locustio/locust
    ports:
      - "7999:7999"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/test1.py --master -H http://host.docker.internal:8001

  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/test1.py --worker --master-host master